# Wayland / Hyprland
gpu-context=wayland
vo=gpu

# Hardware decoding
hwdec=auto

# ModernZ
osc=no
title-bar=no

# Playback
save-position-on-quit=yes
keep-open=always

# Window
autofit-larger=80%x80%

# mpv 原生 OSD
osd-font-size=12
osd-font="Maple Mono NF CN"

# mpv lua
script-opt=stats-font_size=12
script-opt=console-font_size=12

# 字幕
sub-font-size=16