[Metadata]
Name=cozy
Version=0.1
Author=irmenth
Description=A cozy soft theme for Hyprland
ScaleWithDPI=True

[InputPanel]
EnableBlur=False
NormalColor=#ffffff
HighlightCandidateColor=#1e1e1e
Spacing=0

[InputPanel/Background]
Image=panel.svg

[InputPanel/Background/Margin]
Left=20
Right=20
Top=20
Bottom=20

[InputPanel/Highlight]
Image=highlight.svg

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=10
Right=10
Top=15
Bottom=15

[InputPanel/TextMargin]
Left=10
Right=10
Top=5
Bottom=5
