[Metadata]
Name=cozy
Version=1
Author=irmenth
Description=A cozy soft theme for Hyprland
ScaleWithDPI=True

[InputPanel]
EnableBlur=False
NormalColor=#ffffff
HighlightCandidateColor=#1e1e1e

[InputPanel/Background]
Image=panel.svg

[InputPanel/Background/Margin]
Left=19
Right=19
Top=19
Bottom=19

[InputPanel/Highlight]
Image=highlight.svg

[InputPanel/Highlight/Margin]
Left=4
Right=4
Top=4
Bottom=4

[InputPanel/ContentMargin]
Left=10
Right=10
Top=15
Bottom=15

[InputPanel/TextMargin]
Left=10
Right=10
Top=5
Bottom=5